---
language: python
services: docker

env:
  global:
    - MOLECULE_NO_LOG: "false"
  matrix:
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  - cd ../ && mv ansible-logger juju4.logger
  - cd juju4.logger

script:
  - molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
