---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:18.04}
    env:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
  lint:
    name: ansible-lint
    enabled: true
    options:
      x:
        - 303
# FIXME! To review later
        - 204
        - 301
        - 502
        - 303
# mrlesmithjr
        - 503
        - 702
        - 703
        - 305
# mysql
        - 206
        - 601
        - 602
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
